### PR TITLE
Add --runtime arg. to chaos runner and deployment templates

### PR DESCRIPTION
**Pull request by alfonsomthd**
Signed-off-by: Alfonso Martínez <almartin@redhat.com>

### CODE REVIEW

**Comment by alfonsomthd** [comment]
@JohnStrunk Could you please review? (Not able to add you as reviewer :thinking: )

**Review by JohnStrunk — APPROVED** [review]
I understand the desire to configure it with a fixed runtime (yielding a pass/fail indication), but I don't think that's really the way to get the most value from the tool.
The best approach is to have it as an "always running" job, with termination indicating failure. Quality metric is "how long can it run until the system fails?"

**Comment by alfonsomthd** [comment]
> I understand the desire to configure it with a fixed runtime (yielding a pass/fail indication), but I don't think that's really the way to get the most value from the tool. The best approach is to have it as an "always running" job, with termination indicating failure. Quality metric is "how long can it run until the system fails?"

@JohnStrunk The need for a fixed runtime is for executing the tool in a CI job that needs to finish. I see your point,
so let me know if this possible workaround works for you:
* Simulate the "always running" behavior by setting a huge amount of seconds as default (i.e. 1 year = 31,536,000 seconds). 

Otherwise we can always override the default:
```helm install workload ./helm/ocs-monkey-generator --set chaos.enabled=true --set chaos.runtime=31536000```

**Comment by JohnStrunk** [comment]
Yes, that's workable. A followup w/ runtime=0 as infinite would also be great.

**Pull request merged**
